import { Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer, Slide } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weights: ["100", "400", "500", "600", "700"],
});

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  weights: ["100", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Tobiloba Ibraheem",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${jetBrainsMono.variable} antialiased`}
      >
        <ToastContainer
          position="bottom-center"
          autoClose={4000}
          hideProgressBar={false}
          closeOnClick
          transition={Slide}
          theme="dark"
        />
        {children}
      </body>
    </html>
  );
}
