import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer, Slide } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { FloatingNav } from "@/components/ui/FloatingNavbar";
import Footer from "@/components/views/Footer";
import ChatFeature from "@/components/ui/Chat";

const geistSans = localFont({
  src: [
    {
      path: "../../public/fonts/Geist-VariableFont_wght.ttf",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-geist-sans",
  display: "swap",
});

const jetBrainsMono = localFont({
  src: [
    {
      path: "../../public/fonts/JetBrainsMono-VariableFont_wght.ttf",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

export const metadata = {
  title: "Tobiloba Ibraheem",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${jetBrainsMono.variable} antialiased`}>
        <FloatingNav />
        <ToastContainer position="bottom-center" autoClose={4000} hideProgressBar={false} closeOnClick transition={Slide} theme="dark" />
        {children}
        <ChatFeature />
        <Footer />
      </body>
    </html>
  );
}
